### ISSUE TITLE
Detect remote adress when running behind load balancer

### ISSUE THREAD

**Issue by bratkartoffel** [dennylin93/rcguard#12]
Hi,
currently I got my roundcube running behind a loadbalancer.
The call to $_SERVER['REMOTE_ADDR'] always return the ip of my loadbalancer, not the real client who is trying to login.
The extra headers, X-Real-IP and X-Forwarded-For, are ignored in this plugin.

Regards,
Simon

**Comment by Maxqia** [comment]
Does this repository fix it for you? https://github.com/dsoares/rcguard

**Comment by dennylin93** [comment]
Fixed in commit 53633c723f.
