### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by angelkiller2** [dennylin93/rcguard#18]
After installing/activating Plugin and mysql settings roundcube doesn' t work anymore. It is showing a blank page. In roundcube errorlog i see:

PHP Fatal error:  Call to undefined method rcube_utils::remote_addr() in /usr/share/roundcube/plugins/rcguard/rcguard.php on line 47

**Comment by dennylin93** [comment]
Which version of Roundcube are you using?

**Comment by angelkiller2** [comment]
I am using Roundcube Webmail 0.9.5. It is a Ubuntu Server installation with 15.04 with ISPConfig 3 from this tutorial:

https://www.howtoforge.com/tutorial/perfect-server-ubuntu-15.04-with-apache-php-myqsl-pureftpd-bind-postfix-doveot-and-ispconfig/3/

All steps done from this howto also the installation of roundcube. After that i anstalled the rcguard from this tutorial into my plugin folder of roundcube:

http://notes.sagredo.eu/node/35#rcguard

After activating in roundcube config i see the blank page with PHP Fatal error in roundcube log, that mean there is a undefined method rcube_utils::remote_addr().

The Server is behind a firewall, he has no public IP. But i dont know this is the problem of the undefined call.

**Comment by dennylin93** [comment]
The function rcube_utils::remote_addr() is only available from Roundcube 1.1. Change it to rcube_utils::remote_ip() although it would be better to upgrade to a supported version.

**Comment by dennylin93** [comment]
Close issue due to inactivity.
